### ISSUE TITLE
Screen space reflections?

### ISSUE THREAD

**Issue by Ben-Mack** [pmndrs/postprocessing#190]
Please consider implementing screen space reflections, it would be an amazing addition to improve Three.js realistic factor.

I've found some good sample, tutorial about SSR:
https://github.com/Domenicobrz/WebGL2-Screen-space-reflections
https://lettier.github.io/3d-game-shaders-for-beginners/screen-space-reflection.html 

Related thread: https://github.com/mrdoob/three.js/issues/8248

**Comment by vanruesc** [comment]
Thanks for the references. I can't say that I'm a fan of SSR, but I'll consider adding it.

**Comment by Mykita** [comment]
Just wanted to **+1** the SSR request

**Comment by todaylg** [comment]
Just wanted to +1 the SSR request

**Comment by Ben-Mack** [comment]
I've found an in-progress working implement for Three.js here: https://github.com/gkjohnson/threejs-sandbox/tree/master/screenSpaceReflectionsPass
The result is lacking blurring by roughness, but it does look very promising.
Maybe you could use it as a base to develop on?

**Comment by vanruesc** [comment]
Thanks, that implementation does look pretty good 👌 My current plan is to finish the `SSAOEffect`, improve the `ToneMappingEffect` and then start working on SSR.

**Comment by gonnavis** [comment]
@vanruesc Looking forward to!

**Comment by jcguarinpenaranda** [comment]
+1 :D

**Comment by gonnavis** [comment]
I wrote my own and make a [pr to three.js](https://github.com/mrdoob/three.js/pull/20061), but now just support OrthograhicCamera, I'm trying to support PerspectiveCamera.

**Comment by veryprofessionaldodo** [comment]
Just here to add my +1. I'm currently experimenting with this framework for the company that I work with, and SSR would be quite beneficial!

**Comment by vinkovsky** [comment]
Hi! This will be super useful! is it currently under development?

**Comment by vanruesc** [comment]
See [this comment](https://github.com/vanruesc/postprocessing/issues/279#issuecomment-800973576) for the current plans regarding SSR.

I haven't forgotten about it, but it's currently not a great time to use SSR with `three`. The point of SSR is to render reflections without having to render the scene multiple times. This is currently not possible because `three` doesn't support MRT yet. Even if we were to implement SSR right now, we'd still have to render the scene many times to gather the various textures that are required to render the effect. You'd be better off using a [CubeCamera](https://threejs.org/examples/webgl_materials_envmaps_parallax.html) or a [Reflector](https://threejs.org/examples/?q=reflect#webgl_mirror).

**Comment by DolphinIQ** [comment]
@vanruesc Hi, youre doing awesome work in this repo! Just wanted to let you know MRT landed in three.js r129! Will this change priority of any features, like SSR?

**Comment by vanruesc** [comment]
@DolphinIQ Hey, thanks! The priority of SSR doesn't really change, but MRT definitely opens up a path to an efficient implementation. We still need a reliable way to modify three's built-in materials, e.g. via [NodeMaterials](https://github.com/mrdoob/three.js/issues/16440), to make effective use of this feature. Related comment: https://github.com/vanruesc/postprocessing/issues/292#issuecomment-835860642.

**Comment by vanruesc** [comment]
Closing in favor of #571.
