### ISSUE TITLE
Mixins for handling selective effect ?

### ISSUE THREAD

**Issue by swingingtom** [pmndrs/postprocessing#325]
### Main Question
Are you planning the generalization of `selective` effect ?

I never used `SelectiveBloomEffect` but used some multi pass effects with layers/selections ( just as you described with this https://codesandbox.io/s/quirky-albattani-khdqq?file=/src/App.js  ) 

So currently, we can only have 'native' selection with BloomEffect, but for other effects we should build them ourself.

### Describe the solution you'd like

If they both behave as the same as ( SelectiveBloomEffect and the provided codesandbox ) wouldnt it be better to offer a more generalized way of selection/exclusion for any effects ? 

### Describe alternatives you've considered

Mixins are a just an example here, but allowing (project side) any effect being `selective` would really be great.
```
const SelectiveBloomEffect = PP.SelectiveMixin.extends(BloomEffect);
const MySelectiveEffectClass= PP.SelectiveMixin.extends(NoiseEffect);
```

### Additional context

A recent issues pointed out it wasn't easy to learn from demos, then the `selective` could be handled as a exemple itself, working on any effect, rather than being inside Bloom Demo. 

### Additional notes

Would it make sense to also have selective pass ?

Thx for this library !

**Comment by vanruesc** [comment]
> allowing (project side) any effect being selective would really be great.

I agree, but I'm not sure if this can be generalized. Different effects rely on different data. For example, SSAO uses depth and normals while color grading only uses the scene color. Those effects probably require different masking solutions to support selections.

> If they both behave as the same as ( SelectiveBloomEffect and the provided codesandbox ) 

They don't behave the same: the sandbox does solve selective noise for this particular use case but the depth information of the first render pass doesn't affect the second one. Blending is done based on alpha to work around this, but the objects in `selectionB` cannot occlude the objects in `selectionA`.

It's worth mentioning that implementing efficient selective bloom wasn't trivial. The first version was similar to [three's selective bloom example](https://github.com/mrdoob/three.js/blob/dev/examples/webgl_postprocessing_unreal_bloom_selective.html) which does the following:
1. Render all objects in the scene with a black material
2. Render the selected objects with the original materials
3. Generate the bloom overlay
4. Render the entire scene with the original materials again
5. Apply the bloom overlay

The current `SelectiveBloomEffect` only renders the depth of selected objects and then uses this information to mask out other objects resulting in a much better computational complexity since it's no longer tied to the number of objects in the scene.

I feel like SSAO might require similar treatment to support selections. Maybe it's possible to generalize selective post effects, but I currently don't know how; that would require some experimentation and research.

**Comment by swingingtom** [comment]
Thanks for replying. 
I unfortunately didn't know enough about shaders and postprocessing technics to really be helpful on that. 
At least Im able to ask and try to give an impulse.

I will keep you inform if I need to implements such things, I won't be as qualitative as this library expects it to be, but it could give some leads to debate.

**Comment by vanruesc** [comment]
No problem, I appreciate the input!

**Comment by vanruesc** [comment]
Closing this since there doesn't seem to be an easy way to achieve general selectiveness for arbitrary effects.

However, I plan on adding support for rendering object IDs to texture which could serve as a basis for accurate masking in effects like Bloom and Outline.
