### ISSUE TITLE
Stop using legacy three.js classes

### ISSUE THREAD

**Issue by marcofugaro** [pmndrs/postprocessing#364]
### Is your feature request related to a problem?

If a user is using a custom build of three.js which doesn't include `src/Three.Legacy.js`, this error happens when including postprocessing:

<img width="1188" alt="Screenshot 2022-04-19 at 10 53 13" src="https://user-images.githubusercontent.com/7217420/163980840-f1ebc3e8-81fd-4161-b918-13bbe4ed81b1.png">

This is because postprocessing is still using legacy classes which I think it's wrong.

### Describe the solution you'd like

The three.js peerDependency should be updated to support three.js versions with the new classes only (`>= 0.138.0`).

https://github.com/pmndrs/postprocessing/blob/daba8ea41d4d45857658e39d60fce9fe3c940848/package.json#L85

More precisely, `DataTexture3D` has been renamed to `Data3DTexture` in https://github.com/mrdoob/three.js/pull/23498 and released in **r138**.

`WebGLMultisampleRenderTarget` has been removed in https://github.com/mrdoob/three.js/pull/23455 and released in **r138**.

I can make a PR if this is agreed upon.

### Describe alternatives you've considered

Including the legacy code in my three.js custom build.

**Comment by vanruesc** [comment]
Postprocessing relies on these legacy classes to ensure backward-compatibility with older vesions of `three`. Dropping this code and raising the peer dependency would be a breaking change because the library [would then crash for people who are still using r137 or older](https://github.com/mrdoob/three.js/issues/23612#issuecomment-1054323897).

Under normal circumstances, I would just release a new major version, but I think that people expect the next major version to include most of the changes outlined in the roadmap and dropping the use of legacy code is not a pressing issue so it'll have to wait a bit longer.

As a temporary solution, you could include the required legacy classes in your custom `three` bundle:

```js
// @todo Remove when postprocessing v7 lands.
export class DataTexture3D extends Data3DTexture {

	constructor( data, width, height, depth ) {

		super( data, width, height, depth );

	}

}

// @todo Remove when postprocessing v7 lands.
export class WebGLMultisampleRenderTarget extends WebGLRenderTarget {

	constructor( width, height, options ) {

		super( width, height, options );
		this.samples = 4;

	}

}
```

**Comment by marcofugaro** [comment]
Right, didn't understand you needed to publish a major version when bumping the minimum required three.js version.

I'll wait for the next major release in that case.
