### ISSUE TITLE
Make Pass.dispose() predictable

### ISSUE THREAD

**Issue by wmcmurray** [pmndrs/postprocessing#381]
### Is your feature request related to a problem?

I stumbled upon this problem twice recently, it's basically the `Pass.dispose()` method here :
https://github.com/pmndrs/postprocessing/blame/877cda9c93aa3ed6106062e0010674c1641a56a7/src/passes/Pass.js#L371-L388

While it feels nice to loop over every props and magically call their dispose method, it also introduce unpredictable outcomes which are often very hard to locate. The base `Pass` class doesn't _really_ know what needs to be disposed (nor in which order they should be), it doesn't know which props third-party passes will implement either, therefore it shouldn't have this responsibility !

### Describe the solution you'd like

Every pass should be responsible for **explicitly** disposing their own ressources.

This can either be done by defining a `dispose` method in every passes or, what I like in scenarios like this, is to implement a method to register things that will need to be disposed once the dispose method is called. 

This way every passes could define (in their constructor, or else) what requires disposal, something like this:

```js
constructor() {
  // ...
  
  // this will populate an array (this._disposables) of objects with a dispose method
  this._registerDisposables(
    this.renderPass,
    this.renderTarget,
  );
}
```

And the `Pass.dispose` method would look like this :

```js
dispose() {
  while(this._disposables.length) {
    this._disposables.pop().dispose();
  }
}
```

It's just a suggestion, you can do however you like 🙂 

### Additional context

Some occurrence of this problem I've witnessed :

- unwanted renderer.dispose call : https://github.com/pmndrs/postprocessing/issues/353#issuecomment-1057370495
- unwanted composer.dispose call, resulting in an infinite loop : https://github.com/0beqz/screen-space-reflections/pull/3
- in my project, there is a dispose method on my camera, it was called without my consent when I disable postprocessing, breaking things unexpectedly

**Comment by vanruesc** [comment]
I agree.

The approach with `_disposables` used to be a thing but it got replaced by the current approach due to its simplicity. The point of this method is to free GPU resources, namely shader programs, textures and render targets. However, the redesign in the next major release will change how render targets and textures are declared by passes and effects and that will allow for better resource management. The disposal of render targets will move to a centralized buffer manager and the dispose method will no longer be needed for the most part. It will still be possible to override the `dispose` method to free custom resources, but the current default logic will be removed.

**Comment by vanruesc** [comment]
Made `dispose` less destructive as a temporary solution in `postprocessing@6.28.2`.
