### ISSUE TITLE
protected members in Pass -> public

### ISSUE THREAD

**Issue by alexpineda** [pmndrs/postprocessing#391]
In my project I re-use passes and effects with different cameras and with the new types (Thank You!) I'm having to `// @ts-ignore` the assignment since they are protected. Would it be acceptable to have these fields public? Alternatively I could clone the passes/effects, however it causes a pause on initial compile/upload when switching views. I could pre-render them all to upload them all at once as well to avoid the issue perhaps.

```ts
updatePostProcessingCamera(camera: Camera, renderLastPassToScreen: boolean) {
        let lastPass: any = null;

        for (const pass of this.passes) {
            // @ts-ignore
            pass.camera = camera;
            pass.renderToScreen = false;
            if (pass.enabled) {
                lastPass = pass;
            }
        }
        lastPass.renderToScreen = renderLastPassToScreen;

        // some effects have cameras eg. DepthOfFieldEffect
        for (const effect of this.effects) {
            // @ts-ignore
            if (effect.camera) {
                // @ts-ignore
                effect.camera = camera;
            }
        }

    }
    ```

**Comment by vanruesc** [comment]
The `camera` field is protected because some passes/effects use materials that copy some of the camera settings like `near`, `far` and the camera type during initialization. Changing the field to public would require additional logic to make sure the inner materials are kept up-to-date. Actually, I'd prefer to remove the `camera` parameters from passes and effect if possible. It would be nice if the main camera and scene could be set in one place, like the upcoming `RenderPipeline`.

I'll think of something, but suggestions are of course welcome. Use case examples like this one are very helpful in designing the API.

**Comment by vanruesc** [comment]
Added `EffectComposer.setMainScene()` and `EffectComposer.setMainCamera()` in `postprocessing@6.29.0`.
