### ISSUE TITLE
threejs example reports an error or does not load properly after using postprocessing

### ISSUE THREAD

**Issue by aile1997** [pmndrs/postprocessing#457]
### Description of the bug

I've had problems with both of the examples I've used so far, water and lensflares.

### To Reproduce

https://threejs.org/examples/#webgl_lensflares
https://threejs.org/examples/?q=water#webgl_water

### Expected behavior

They load normally when using threejs' built-in post-processing

### Screenshots

![image](https://user-images.githubusercontent.com/78535301/223303374-bb0eb4ec-7da0-4d4f-9672-cc6c019bab5b.png)
![image](https://user-images.githubusercontent.com/78535301/223303479-988c0767-b8c0-4bf6-b23f-a0753fa976a8.png)

### Library versions used

 - Three:0.150.1
 - Post Processing: 6.30.1

**Comment by vanruesc** [comment]
Three's postprocessing passes are **not** compatible with this library. You might get them to work if you tinker with their render methods:

```js
THREE.VelocityDepthNormalPass.prototype = Object.assign(THREE.VelocityDepthNormalPass.prototype, {
	initialize: function() {},
	setRenderer: function() {},
	getDepthTexture: function() {},
	setDepthTexture: function() {},
	originalRender: THREE.VelocityDepthNormalPass.prototype.render,
  	render: function(renderer, inputBuffer, outputBuffer, delta, maskActive) {
		this.originalRender(renderer, outputBuffer, inputBuffer, delta, maskActive);
	}
});
```

**Comment by vanruesc** [comment]
Closing this as answered.

**Comment by aile1997** [comment]
Sorry, I just saw it. Thank you very much for your answer. Could you please give me a more detailed example? Or is there a simple way I could render these effects through another channel without any post-processing?

**Comment by vanruesc** [comment]
Lens flares are on the roadmap #279, but there are currently no plans to add an alternative for water rendering.

Having that said, three's water objects should work with `postprocessing` no problem. The error you're getting is likely related to a misconfiguration, since [updateFlow](https://github.com/mrdoob/three.js/blob/d440449f6a0104e4095a6fee0b1a1e64df3f926a/examples/jsm/objects/Water2.js#L158) doesn't really do anything special. I'm also not sure what `VelocityDepthNormalPass` is and what it's doing, but it might also be causing problems.
