### ISSUE TITLE
SMAAEffect without RenderPass before it

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [pmndrs/postprocessing#499]
### Description of the bug

As the `RenderPass` introduces artefacts, especially when using lines, the `SMAAEffect` cannot work correctly as an already flawed texture is provided as an input. Is it possible to use the  `SMAAEffect` as the first pass?

If there is currently no way, the way forward would probably be to create a `SMAAPass` myself and use it instead of the `RenderPass`?

### To Reproduce

[Example to reproduce the issue](https://codesandbox.io/s/ih5qh7), the lines are not rendered correctly by the `RenderPass`, therefore there is nothing to "fix" by the `SMAAEffect`. 

### Screenshots

Expectation (WebGLRenderer.antialias set to `true` and rendering without postprocessing library):
<img width="826" alt="image" src="https://github.com/pmndrs/postprocessing/assets/40572701/d1762e06-545b-4b43-8793-aec5ed0eee21">

Reality:
<img width="826" alt="image" src="https://github.com/pmndrs/postprocessing/assets/40572701/13112dd4-3d5b-4610-8f61-9c8d278aa5ad">

Thank you for all the help!

**Comment by vanruesc** [comment]
SMAA is an image-based anti-aliasing technique. It can only smooth edges if you provide an input image, which is usually the rendered scene. So rendering SMAA before rendering the scene doesn't make sense.

It's true, that SMAA as well as other similar techniques like FXAA can only work with what's visible in the provided image, so producing extra texels around jagged lines for additional stability is not possible at this render stage.

Have you tried using MSAA instead? This is the same as setting `antialias` to `true` on the canvas, but for the internal buffers. This AA does introduce artifacts with some depth-based effects like SSAO. Fixing that issue is on the roadmap.

```js
const composer = new EffectComposer(renderer, {
  multisampling: 4
}); 
```

**Comment by MajorMeerkatThe3rd** [comment]
Hello @vanruesc 

thank you for the quick reply. Unfortunately I also need the depth-based effects, therefore MSAA is currently not an option for me.

Maybe I'm missing something but doesn't the [three.js SSAARenderPass](https://github.com/mrdoob/three.js/blob/a009b5ec577a0312a55861bd5419941e19eb8578/examples/jsm/postprocessing/SSAARenderPass.js#L22) do exactly as I described. In that case they work with a camera offset and render the scene multiple times, which therefore leads to a better anti-aliasing result.

My idea would be to port this pass to your library to get the same results. Or is there something in the way of that?

**Comment by vanruesc** [comment]
I think TAA would be the better choice in that case.

SSAA is really not great in terms of performance since it needs to render the scene multiple times.

**Comment by MajorMeerkatThe3rd** [comment]
Thanks, I'll have a closer look at that!
