### ISSUE TITLE
Incompatible with new 1.55.0 version

### ISSUE THREAD

**Issue by andrevenancio** [pmndrs/postprocessing#518]
On the package.json the peerDependencies do not allow use of new 1.55.0 version of threejs.

I am not sure if there is any feature on the new version that is incompatible but the way the peerDependencies are setup it doesn't allow for upgrading to the new version.

**Comment by vanruesc** [comment]
The peer dependency version range is a recommendation that indicates versions that are guaranteed to be supported. You can still update to a more recent version of `three` but there's a risk that it may not work because it hasn't been tested yet.

I'm a bit behind on updating `postprocessing` but I'm working on a new release right now.
