### ISSUE TITLE
Transparent background does not work with depth of field effect

### ISSUE THREAD

**Issue by vis-prime** [pmndrs/postprocessing#529]
### Description of the bug

When dof effect is and background is null , background becomes black in 6.33.0

### To Reproduce

[sandbox](https://codesandbox.io/s/dof-forked-3yjyfk?file=/src/index.js) (click the "Update to Latest" 🔄 icon to check the latest release)

### Expected behavior
like the older versions transparency should get maintained

### Screenshots
![older](https://github.com/pmndrs/postprocessing/assets/119810373/8d41f735-d61c-4f3d-acfe-86027c614cb4)
![latest](https://github.com/pmndrs/postprocessing/assets/119810373/61af17bf-9f14-44dc-878a-533edd8282e8)

### Library versions used

 - Three: [e.g. 0.155.0]
 - Post Processing: [e.g. 6.33.0]

### Desktop

 - OS: [Windows]
 - Browser [Version 116.0.5845.141 (Official Build) (64-bit)]
 - Graphics hardware: [NVIDIA]

**Comment by sdraper69** [comment]
I too am facing this issue, and I have noticed another user has raised it ([see here](https://github.com/pmndrs/postprocessing/issues/533)).

Is there an ETA for a fix?

**Comment by vanruesc** [comment]
I thought I fixed this in 479deb1 but it's still not rendering the same way as before when using a transparent canvas.

My guess is that DoF on a transparent background is simply not possible. Upon closer inspection, both of the screenshots above look wrong. This issue is similar to #387 and supporting the previous behaviour would mean breaking the correct opaque behaviour :thinking:

**Comment by vis-prime** [comment]
so the options are

keep antialiasing but bg cannot be transparent
or
keep transparency but antialiasing won't work

?

**Comment by sdraper69** [comment]
If it can't be optional, then I would think that keeping transparency but switching antialiasing off would be best. My reasoning would be if people are using DoF then things generally will be getting blurry so you may not even notice the AA missing?

**Comment by vanruesc** [comment]
Sorry, I should've been more clear: the problem is that DoF doesn't work properly on a transparent canvas. The result is always wrong because the shader can't access the colors behind the canvas. Other convolution effects like SMAA and FXAA have the same issue.

I've added a `maskFunction` option in `postprocessing@6.33.1` which can be used to restore the alpha blend behaviour:

```js
import { MaskFunction } from "postprocessing";
dofEffect.maskFunction = MaskFunction.MULTIPLY;
```

Please note that this setting will be removed in the next major version.

**Comment by vanruesc** [comment]
> dofEffect.maskFunction is currently undefined

Oh, the `MaskMaterial` doesn't have a getter for this. Thanks for pointing that out!

> alpha is working correctly anyway

The masking no longer changes the alpha of the far scene, but the blending also doesn't account for alpha blurring anymore. Changing the mask function to multiply (RGBA) restores the [old blending behaviour](https://github.com/pmndrs/postprocessing/blob/a686017a6a60bb66cca900f913051b11424ffa0f/src/effects/glsl/depth-of-field.frag#L22-L28) which produces different results depending on the scene.

> Do you mean that in next major version DOF will not work with transparent background?

DoF already does not work with a transparent background. What you're seeing is just the background showing through without correct blurring and blending. The old alpha blending produces halos around objects. The `maskFunction` setting was only added to reduce update friction.

**Comment by lviggiani** [comment]
Thank you for the explanation!

> DoF already does not work with a transparent background. What you're seeing is just the background showing through without correct blurring and blending. The old alpha blending produces halos around objects. The maskFunction setting was only added to reduce update friction.

I didn't notice that as my transparent canvas sits on top of a flat white color rather than a texture as in the example above :)
