### ISSUE TITLE
OutlineEffect only on selected instanced meshes indexes

### ISSUE THREAD

**Issue by naive17** [pmndrs/postprocessing#530]
This is not a real bug and i'm kinda sorry for this.
I was wondering if there's some known way to make the outline selection pass works only on few selected indexes of a instanced mesh.
In my case i make heavy use of instanced meshes on highly repeated objects inside a editor and i wish to outline on hover on said elements.
Is there any way possible?
Thanks for the time, the kindness and all the effort for this project!

**Comment by vanruesc** [comment]
Unfortunately, this isn't currently supported due to the way the `OutlineEffect` compares depth of selected objects.

However, I plan on creating a new outline effect in v7 which will support outlining individual instances based on an object ID buffer, but this will be a little further down the road.
