### ISSUE TITLE
Is DepthEffect Working?

### ISSUE THREAD

**Issue by bytesbay** [pmndrs/postprocessing#554]
### Description of the bug

Hey everyone!

I'm new to GLSL and postprocessing, just playing with custom effects, and noticed that DepthEffect always shows white just background with no details.

Is DepthEffect Working with latest version?

### To Reproduce

```typescript

// ...

const depth = new DepthEffect({
    
});

composer.addPass(new RenderPass(scene, camera));
composer.addPass(new EffectPass(camera, depth));

// ...

```
### Expected behavior

A grey scale image where dark is the far layer and white is closest layer

### Library versions used

 - Three: 0.155.0
 - Post Processing: 6.33

### Desktop

 - OS: MacOS
 - Browser Arc Browser (Chromium)
 - Graphics hardware: M1

**Comment by vanruesc** [comment]
Hi, this is working as expected.

The `DepthEffect` is usually used for debugging. Objects that close to the camera will appear black/grey since their fragments have low depth values. Everything else will be mostly white due to the depth distribution of the depth buffer (see https://www.reedbeta.com/blog/depth-precision-visualized/)
