### ISSUE TITLE
EffectPass in composer changes rendering of DataTexture in scene

### ISSUE THREAD

**Issue by timmevandermeer** [pmndrs/postprocessing#565]
### Description of the bug

Adding an EffectPass to the EffectComposer changes the brightness of a DataTexture, but does not affect the color of other meshes. Things look correct without the EffectPass, but introducing it seems to change how the texture data is interpreted somehow.

### To Reproduce

I wasn't yet able to recreate a simple reproduction, as the issue occurs in an application with multiple scissored viewports that uses react-three-fiber but not react-postprocessing as it doesn't play nicely with the scissored views. I was hoping somebody could guess what is going on based on the following:

I have a basic composer setup, in this case leaving the effects out
```ts
const composer = new EffectComposer(renderer);
const render = new RenderPass(scene, camera);
composer.addPass(render);
const effectPass = new EffectPass(camera);
composer.addPass(effectPass);
```

and the following gl config:

```ts
{
  powerPreference: "high-performance",
  preserveDrawingBuffer: true,
  stencil: false,
  depth: true,
  toneMapping: NoToneMapping,
  premultipliedAlpha: false,
}
```

The data texture is created as follows:

```ts
const texture = new Data3DTexture(image, columns, rows, numberOfFrames);
texture.format = RedFormat;
texture.magFilter = LinearFilter;
texture.needsUpdate = true;
```

It is rendered using a custom shader on a plan that samples the 3D texture:

```glsl
vec4 color = texture(
  data,
  vec3(dataCoordinatesNormalized.x, dataCoordinatesNormalized.y,1.-dataCoordinatesNormalized.z)
);
```

I tried adjusting things like `.encodeOutput` for the effectPass, or using different `inputColorSpace` / `outputColorSpace` for the Effects but these all changed the overall colors of the rendered output, not just the texture.

### Screenshots

Data3DTexture slice rendered without effect pass
![image](https://github.com/pmndrs/postprocessing/assets/7414434/0758d7cf-b3c7-47db-b57e-244a6b0ed44f)

Data3DTexture slice rendered with effect pass (too bright)
![image](https://github.com/pmndrs/postprocessing/assets/7414434/20285c80-a3e2-44b1-9f34-e8af3101a1f2)

Meshes rendered without effect pass
![image](https://github.com/pmndrs/postprocessing/assets/7414434/7418b192-a11d-4989-9479-e1adf579884a)

Meshed rendered with effect pass (unaffected)
![image](https://github.com/pmndrs/postprocessing/assets/7414434/43b9b71d-2700-4d7d-8ed8-f4092c36a5cb)

### Library versions used

 - Three: 0.159.0
 - Post Processing: 6.33.4
 - r3f: 8.15.12

### Desktop

 - OS: MACOS
 -  Browser: Chrome 120
 - Graphics hardware: Macbook Pro M1

**Comment by timmevandermeer** [comment]
I did find that doing an srgb to linear conversion in the shader does mostly corrects the texture intensity / colors. But I still wonder what happens to cause this issue to begin with

**Comment by vanruesc** [comment]
> It is rendered using a custom shader on a plane that samples the 3D texture

The following assumes that this plane is part of the scene.

Three's built-in shaders include color space conversion code which only gets executed when rendering to the canvas. This is the case when using a single `RenderPass`. If the scene is rendered to an off-screen buffer instead, colors won't be converted and they'll be written as-is (`LinearSRGBColorSpace`). The `EffectPass` also includes color conversion code which gets executed when rendering to the canvas.

In your case, the first situation with only a `RenderPass` technically produces wrong results by rendering the image without the proper conversion to sRGB because your shader is lacking that code. You can fix this by adding [#include <colorspace_fragment>](https://github.com/mrdoob/three.js/blob/2ab27ea33ef2c991558e392d4f476ac08975be0d/src/renderers/shaders/ShaderLib/meshbasic.glsl.js#L110C2-L110C32). DataTextures use `NoColorSpace` by default. You can use `SRGBColorSpace` instead to counteract the final conversion to sRGB.
