### ISSUE TITLE
Shader colors are brighter

### ISSUE THREAD

**Issue by nrbrttth** [pmndrs/postprocessing#613]
### Description of the bug

I have a terrain with MeshStandardMaterial, and with onBeforeCompile I apply a modification to highlight the current target entity on it. I pass the highlight color as a uniform. Additionally if fog is enabled, it seems brighter too.

### To Reproduce

I put together a simple example:
https://codesandbox.io/p/sandbox/goofy-colden-6c8pnm
You can see if you enable smaa, the shape will be way brighter. Same with fog.
It's not SMAA specific, it's just an example. The same issue appears if I add any other effect.

### Expected behavior

I expected it to be the same color, as I modify gl_FragColor in the fragment shader.

### Screenshots

Without postprocessing it looks like this:
![image](https://github.com/pmndrs/postprocessing/assets/23727847/aea442f2-0cbc-4858-b540-b05a202d8b75)
And with just one SMAAEffect:
![image](https://github.com/pmndrs/postprocessing/assets/23727847/893afe58-2d71-4760-bea2-fc6bc0e5e09b)

### Library versions used

 - Three: [0.162.0]
 - Post Processing: [6.35.1]

### Desktop

 - OS: [Windows 11]
 - Browser [Edge 122.0.2365.80]
 - Graphics hardware: [NVIDIA 3060 RTX]

**Comment by vanruesc** [comment]
Your custom shader code should be added after `<opaque_fragment>`. Adding it after dithering circumvents `<colorspace_fragment>`. To get the desired color, you'll need to convert your selection color from sRGB to linear-sRGB: 

```js
selectedEntityColor: { value: new THREE.Color("#ff5757").convertSRGBToLinear() }
```

The same applies to fog when using `postprocessing` because fog circumvents color space conversion in vanilla `three`.

Updated sandbox: https://stackblitz.com/edit/postprocessing-v6-hafpwq?file=src%2Findex.js

**Comment by nrbrttth** [comment]
Thank you for the explanation, makes sense!
