### ISSUE TITLE
`mipmapBlurPass` is not exposed on `BloomEffect`

### ISSUE THREAD

**Issue by hybridherbst** [pmndrs/postprocessing#639]
### Description of the bug

To adjust bloom radius dynamically, I think one has to access
`bloom.mipmapBlurPass.radius = ...`
similar to how it works for luminance,
`bloom.luminanceMaterial.smoothing = ...`

However, the `mipMapBlurPass` is not exposed / not in the types at the moment. Is that intentional?

### Library versions used

 - Three: [e.g. 0.162]
 - Post Processing: [e.g. 6.35.5]

**Comment by vanruesc** [comment]
Hi, thanks for pointing that out.

The [mipmapBlurPass](https://github.com/pmndrs/postprocessing/blob/3140afb6c81387ed2c473bedb06dcc21ca541021/src/effects/BloomEffect.js#L96-L103) property is currently marked as private because it was an experimental feature when it was first added. I'm fine with changing the field to public-readonly. Feel free to send a PR if you'd like. Otherwise, I'll take care of it when I get a chance.
