### ISSUE TITLE
 Lens flare is not visible

### ISSUE THREAD

**Issue by JohMun** [pmndrs/postprocessing#640]
###  Lens flare is not visible

If I use a pass (e.g., BlurPass) together with lens flares, they are not rendered. I made two examples. In the first example, we see lens flares together with a blur pass. It works because I add the pass after 1ms, and the camera looks at the lens flare.  If we remove the timeout or if we don't focus on the lens flares with the camera when the pass is added, the lens flares wouldn't be visible. 

We see this behavior in the second example.

(If I reproduce this locally on my computer a get this warning in the console:
`[.WebGL-00001AC004576200] GL_INVALID_OPERATION: Invalid copy texture format combination.`)

1. Lens flare is visible.
https://jsfiddle.net/am253w4h/157/

2. Lens flare is not visible, but it should be.
https://jsfiddle.net/edzsmnb3/1/

![image](https://github.com/pmndrs/postprocessing/assets/20238661/b88a9a9a-a423-4954-9d5b-92e7e01f63c6)
![image](https://github.com/pmndrs/postprocessing/assets/20238661/db7eca5f-d17a-4cb5-9dbf-a8415eecb8a6)

### Library versions used

 - Three: 0.165.0
 - Post Processing: 6.35.5

### Desktop

 - OS: Windows 11
 - Browser Chrome 125.0.6422.142

**Comment by vanruesc** [comment]
Hi, thanks for the report.

The demo seems to work in Firefox on my system. I'm not sure what's going on in Chrome. The LensFlare addon isn't particularly compatible with postprocessing in general which is why there are plans to implement a `LensFlareEffect` as an alternative.

Related: https://github.com/pmndrs/postprocessing/issues/308#issuecomment-894814665

**Comment by JohMun** [comment]
Okay, thx, then I'll close this issue, because it's kind of a duplicate.
