### ISSUE TITLE
How to access custom geometry attributes in Custom Effects?

### ISSUE THREAD

**Issue by augusttty** [pmndrs/postprocessing#658]
Hi,i'm recently testing with SelectiveBloom Effect with instancedMeshes, to achieve single-instance bloom, i defined a custom InstancedBufferAttribute(named "isShine") on each instancedMesh. Then i need to access the "isShine" attribute in  effect's frag-shader. But how?Any help will be appreciate, thanks.

**Comment by augusttty** [comment]
I've realized that we cannot access attribute in a fullscreen pass

**Comment by vanruesc** [comment]
Hi, sorry for the late reply!

You're right, you can't access the attributes at that stage, but you can use another approach:
- Maintain two identical instanced meshes.
- Add one of them to the effect's selection.
- Manage instances by sorting buffer attributes and utilizing `InstancedMesh.count` to limit the instance draw range.

With this setup you can render selected and non-selected instances at the cost of 2 draw calls instead of one.
